### ISSUE TITLE
Unique cluster

### ISSUE THREAD

**Issue by fedeago** [KrishnaswamyLab/SAUCIE#9]
Hi, i am trying to use saucie to find cluster, i can run the code but it fin only one cluster. I checked,  and after log-transforming the data the maximun is near +11 and the minimun near -4. Someone know why could this happen?

**Comment by mattamodio** [comment]
Hi there, thanks for trying out SAUCIE! The most common reason for that is if the default hyperparameter choices are not optimal for your dataset. I would try reducing the amount of the clustering coefficient, instead of SAUCIE(lambda_c=.1, lambda_d=.2), maybe try SAUCIE(lambda_c=.05, lambda_d=.2) or also increasing the intra-cluster distance coefficient, like SAUCIE(lambda_c=.05, lambda_d=.4). Hope that helps!
